//CREATE TABLE ADDRESS(ID LONG PRIMARY KEY,CREATION Date,CONTENT varchar(255));

INSERT INTO ADDRESS (ID, CREATION, CONTENT,AUTEUR) VALUES (1, CURRENT_TIMESTAMP(), '150 rue des Augustins','Florian');
INSERT INTO ADDRESS (ID, CREATION, CONTENT,AUTEUR) VALUES (2, CURRENT_TIMESTAMP(), '34 avenue Bartholdie,72000 Le mans','Baptiste');
